name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with: 
        fetch-depth : 0


    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "Starting Process"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
        echo "Finishing Process"

    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t xxwataryxx/docker-graphql:$NEW_VERSION .
        docker build -t xxwataryxx/docker-graphql:latest .

        
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push xxwataryxx/docker-graphql:$NEW_VERSION
        docker push xxwataryxx/docker-graphql:latest
